name: Flint Creative
favicon: null
layout_spectrum: 0.731493836035952
typography_spectrum: 0.05205087037757039
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffcf3'
    - '#040404'
    - '#bfc2c7'
    - '#2b414e'
    - '#58788a'
  brandStrength: 0.6875
  lightness: 0.26508221286349
  saturation: 0.4375
  rhythmicContrast: 0.188797710230574
purpose: []
